version: '3.8'

services:
  discovery-service:
    container_name: discovery-service
    image: discovery-service
    build: ./discovery-service
    ports:
      - "8761:8761"
    hostname: discovery-service
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    networks:
      - microservices-network
  config-service:
    container_name: config-service
    image: config-service
    build: ./config-service
    ports:
      - "8888:8888"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
    networks:
      - microservices-network

  mysql:
      image: mysql:8.0
      container_name: mysql-db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
      ports:
        - "3306:3306"
      networks:
        - microservices-network
      volumes:
        - mysql-data:/var/lib/mysql

  # phpMyAdmin (Interface de gestion MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    networks:
      - microservices-network
    depends_on:
      - mysql
  profile-service:
    container_name: profile-service
    image: profile-service
    build: ./profile-service
    ports:
      - "8091:8091"
    environment:
      - HOSTNAME=profile-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/profileService?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - discovery-service
      - mysql
    networks:
      - microservices-network

  api-gateway:
    container_name: api-gateway
    image: api-gateway
    build: ./api-gateway
    ports:
      - "8222:8222"  # Port exposé pour l'API Gateway
    environment:
      - HOSTNAME=api-gateway
      - EEUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery-service:8761/eureka/
    depends_on:
      - discovery-service
      - profile-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge


volumes:
  mysql-data:  # Volume pour persister les données de MySQL