services:
  db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ProductsCategories
    ports:
      - "3307:3306"
    volumes:
      - db-data:/var/lib/mysql

  app:
    build: .
    container_name: spring-app
    ports:
      - "8087:8087"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/ProductsCategories?serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root

volumes:
  db-data:
